### ISSUE TITLE
[HonoInfluxDBConnector] SocketTimeoutException

### ISSUE THREAD

**Issue by phil-hei** [eclipse/kuksa.cloud#55]
Running the HonoInfluxDBConnector for a longer time caused the following exception:

`2019-04-24 14:08:03.694 ERROR 5517 --- [pool-1-thread-1] org.influxdb.impl.BatchProcessor         : Batch could not be sent. Data will be lost

org.influxdb.InfluxDBIOException: java.net.SocketTimeoutException: timeout
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:514) ~[influxdb-java-2.7.jar:na]
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:312) ~[influxdb-java-2.7.jar:na]
        at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:248) ~[influxdb-java-2.7.jar:na]
        at org.influxdb.impl.BatchProcessor$1.run(BatchProcessor.java:202) [influxdb-java-2.7.jar:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [na:na]
        at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: java.net.SocketTimeoutException: timeout
`
Did anyone else stumbled into this kind of issue?

**Comment by selobosi** [comment]
This might be a known issue: https://github.com/eclipse/kuksa.cloud/tree/master/utils/hono-influxdb-connector#known-issues

**Comment by eriksven** [comment]
@selobosi and @unly is this issue solved with one of you upcoming PRs?

**Comment by unly** [comment]
not sure. could be resolved by the rewrite. pr is still pending

**Comment by selobosi** [comment]
I did not address this issue specifically.

**Comment by unly** [comment]
#51 has been merged. feel free to check if the problem still exists

**Comment by eriksven** [comment]
@phil-hei are you able to reproduce the issue with the current version? We run the HonoInfluxDbConnector in our clusters over several weeks without any restart and did not experience the describe behaviour.

**Comment by phil-hei** [comment]
We haven't observed the issue again, probably has been fixed in the meantime. If we notice it again, I'll reopen the issue.
